dev_application_applicationCreate:
    path:     /create
    defaults: { _controller: AppBundle:App:ApplicationCreate }

dev_application_applicationShow:
    path:     /show/{id}
    defaults: { _controller: AppBundle:App:ApplicationShow }

dev_application_applicationUpdate:
    path:     /update/{id}
    defaults: { _controller: AppBundle:App:ApplicationUpdate }

dev_application_applicationDelete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:App:ApplicationDelete }