services:
#    functionality_application.example:
#        class: Functionality\ApplicationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    Functionality_application.form.type.application:
        class: Functionality\ApplicationBundle\Form\Type\ApplicationType\ApplicationType
        tags:
            - { name: form.type, alias: Application }