context_portal_homepage:
    path:     /
    defaults: { _controller: ContextPortalBundle:Portal:home }

context_portal_atest:
    path:     /{name}
    defaults: { _controller: ContextPortalBundle:Default:index }
