context_portal_homepage:
    path:     /
    defaults: { _controller: ContextPortalBundle:Portal:home }

context_portal_article:
    path:     /{slug}
    defaults: { _controller: ContextPortalBundle:Portal:article }
