Functionality\ContentBundle\Entity\Content:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
        date:
            type: datetime
            column: Date
        content:
            type: text
            column: Content
        slug:
            type: string
            length: 255
            column: Slug
        published:
            type: boolean
            column: Published
    manyToMany:
        streams:
            targetEntity: Stream
            inversedBy: contents
            nullable: true
            joinColumn:
                name: stream_id
                referencedColumnName: id
            inverseJoinColumn:
                name: content_id
                referencedColumnName: id
        applications:
            targetEntity: Application
            inversedBy: contents
            nullable: true
            joinColumn:
                name: application_id
                referencedColumnName: id
            inverseJoinColumn:
                name: content_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
