Functionality\ContentBundle\Entity\Stream:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        content:
            targetEntity: Content
            mappedBy: stream
    lifecycleCallbacks: {  }
