Functionality\ApplicationBundle\Entity\Application:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
        type:
            type: string
            length: 255
            column: Type

    lifecycleCallbacks: {  }
