context_portal:
    resource: "@ContextPortalBundle/Resources/config/routing.yml"
    prefix:   /

context_blog:
    resource: "@ContextBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
