_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /dev/app

functionality_content:
    resource: "@FunctionalityContentBundle/Resources/config/routing.yml"
    prefix:   /dev/content

functionality_navbar:
    resource: "@FunctionalityNavbarBundle/Resources/config/routing.yml"
    prefix:   /dev/navbar

_main:
    resource: routing.yml
