<?php

namespace Functionality\NavbarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NavbarLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavbarLinkRepository extends EntityRepository
{
	// function findByNavbar($navbar){
 
 //        $query = $this->createQueryBuilder('navbarLink')
 //                      ->select('navbarLink')
 //                      ->leftJoin('navbarLink.navbars', 'navbar')
 //                      ->addSelect('navbar')
 //                      ->where('navbar = :navbar')
 //                      ->setParameter('navbar', $navbar)
 //                      ->getQuery()
 //                      ->getResult();
          
 //        return $query;
 
 // 	}
}
