dev_app_applicationCreate:
    path:     /create
    defaults: { _controller: AppBundle:App:ApplicationCreate }

dev_app_applicationShow:
    path:     /show/{id}
    defaults: { _controller: AppBundle:App:ApplicationShow }

dev_app_applicationUpdate:
    path:     /update/{id}
    defaults: { _controller: AppBundle:App:ApplicationUpdate }

dev_app_applicationDelete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:App:ApplicationDelete }
