services:
#    app.example:
#        class: AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    app.form.type.application:
        class: AppBundle\Form\Type\ApplicationType\ApplicationType
        tags:
            - { name: form.type, alias: Application }
