# context_blog_homepage:
#     path:     /hello/{name}
#     defaults: { _controller: ContextBlogBundle:Default:index }

content:
    path:     /content
    defaults: { _controller: ContextBlogBundle:Blog:index }
