# context_blog_homepage:
#     path:     /hello/{name}
#     defaults: { _controller: ContextBlogBundle:Default:index }

index:
    path:     /
    defaults: { _controller: ContextBlogBundle:Blog:index }
