Functionality\ArticleBundle\Entity\Article:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name
        content:
            type: text
            column: Content
        slug:
            type: string
            length: 255
            column: Slug
    lifecycleCallbacks: {  }
